### ISSUE TITLE
New user group to add

### ISSUE THREAD

**Issue by seanw122** [ovation22/SpeakerMeet.UI#61]
Tulsa .NET User Group
We meet twice a monthly now that we are virtual.
meetup.com/TulsaDevelopers-net

Thanks!

**Comment by ovation22** [comment]
Added. Thanks!

Let me know if there's a better image, etc.

https://speakermeet.azurewebsites.net/search?terms=tulsa

**Comment by seanw122** [comment]
It's fine. I don't have a better image at the moment.
